name: pss
channels:
  - conda-forge
dependencies:
  - python=3.9
  - google-cloud-sdk
  - jupyter
  - matplotlib
  - mkl-service
  - mmcif_pdbx
  - numpy 
  - pandas=1.3.3
  - pandas-profiling
  - pip
  - pyspark
  - scikit-learn
  - seaborn
  - pip:
    - appdirs==1.4.0
    - biopython==1.68
    - google-api-python-client
    - google-cloud-storage
    - https://github.com/Theano/Theano/archive/master.zip
    - https://github.com/Lasagne/Lasagne/archive/master.zip